<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "projektlayout"
 *
 * Auto generated by Extension Builder 2016-08-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Projekt-Layout',
	'description' => 'Layout Extension',
	'category' => 'plugin',
	'author' => 'Ralf-René Schröder',
	'author_email' => 'ralf.rene@image-format.eu',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-11.5.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);